import { dt, ThemeSwitcher } from '@/features/Theming'
import styled from '@emotion/styled'
import logo from '@/assets/logo.svg'
import wavesMobile from '@/assets/waves-mobile.svg'
import { NavLink, Outlet, useMatch, useNavigate } from 'react-router-dom'
import { useMediaQuery } from '@/hooks'
import { useEffect } from 'react'

const Container = styled.div`
  background: ${dt.theme.background};
  display: flex;
  flex-direction: column;
  gap: 30px;
`

const Header = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`

const LogoWrapper = styled.div`
  width: 100vw;
  height: fit-content;
  background: ${dt.colors.dark};
  display: flex;
  flex-direction: column;
  align-items: center;
  &::after {
    content: url(${wavesMobile});
    display: block;
    width: 100vw;
    background: ${dt.theme.background};
  }
`

const LogoImg = styled.img`
  width: clamp(240px, 70vw, 300px);
  margin-top: 4vh;
`

const LogoTitle = styled.h1`
  font-family: 'Sedgwick Ave Display';
  position: relative;
  font-size: 2.5rem;
  color: #b2e2d8;
  text-shadow: 4px 4px 4px #097382;
  margin: 0;
  margin-top: 20px;
`

const LogoSubtitle = styled.span`
  font-family: 'Mansalva';
  font-size: 0.6em;
  position: absolute;
  left: -1.2em;
  top: -2rem;
  color: ${dt.colors.light};
`

const StyledThemeSwitcher = styled(ThemeSwitcher)`
  align-self: flex-end;
  margin-right: clamp(20px, 5vw, 100px);
  position: relative;
  top: 10px;
`

const Nav = styled.nav`
  display: flex;
  flex-direction: column;
  gap: 40px;
  align-items: center;
`

const StyledNavLink = styled(NavLink)`
  font-family: 'Swanky and Moo Moo';
  font-size: 2.5rem;
  text-decoration: none;
  color: ${dt.theme.primary};
  border: 2px solid ${dt.theme.primary};
  width: fit-content;
  min-width: 13ch;
  padding: 0.5rem 2rem;
  border-radius: 15px;
  text-align: center;

  &:hover,
  &.active {
    background: ${dt.theme.primary};
    color: ${dt.theme.background};
  }
`

const Footer = styled.footer`
  background: ${dt.colors.dark};
  color: ${dt.theme.background};
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-bottom: 20px;
  overflow: hidden;

  &::before {
    content: url(${wavesMobile});
    transform: rotate(180deg) scaleX(140%);
    display: block;
    width: 100vw;
    background: ${dt.theme.background};
  }
`

const FooterText = styled.p`
  margin: 0.25rem;
  font-size: 0.8rem;
  display: block;

  &:first-of-type {
    margin-top: 20px;
  }
`

const Main = styled.main`
  @media only screen and (min-width: 600px) {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 100px;
    margin: 0 100px;
  }
`

const navItems = [
  {
    title: 'Projects',
    path: '/projects',
  },
  {
    title: 'Articles',
    path: '/articles',
  },
  {
    title: 'About',
    path: '/about',
  },
] as const

const Home = () => {
  const isBigScreen = useMediaQuery('only screen and (min-width: 600px)')
  const isRoot = useMatch('/')

  const navigate = useNavigate()

  useEffect(() => {
    if (isBigScreen && isRoot) {
      navigate('/projects')
    }
  }, [isBigScreen, isRoot, navigate])

  const navigation = (
    <Nav>
      {navItems.map(({ title, path }) => (
        <StyledNavLink key={title} to={path}>
          {title}
        </StyledNavLink>
      ))}
    </Nav>
  )

  return (
    <Container>
      <Header>
        <LogoWrapper>
          <LogoImg src={logo} alt='Logo' />
          <LogoTitle>
            <LogoSubtitle>RM's</LogoSubtitle>Flower of Ideas
          </LogoTitle>
          <StyledThemeSwitcher />
        </LogoWrapper>
      </Header>
      <Main>
        {isBigScreen ? (
          <>
            {navigation}
            <Outlet />
          </>
        ) : isRoot ? (
          navigation
        ) : (
          <Outlet />
        )}
      </Main>
      <Footer>
        <FooterText>Created by Real_Marshal</FooterText>
        <FooterText>Logo generated by Midjourney AI</FooterText>
      </Footer>
    </Container>
  )
}

export { Home }
