import logo from '@/assets/logo.svg'
import { Outlet, useMatch, useNavigate } from 'react-router-dom'
import { useMediaQuery } from '@/hooks'
import { useEffect } from 'react'
import {
  Nav,
  StyledNavLink,
  Container,
  Header,
  LogoWrapper,
  LogoImg,
  LogoTitle,
  LogoSubtitle,
  StyledThemeSwitcher,
  Main,
  Footer,
  FooterText,
} from './styles'
import { dt } from '@/features/Theming'

const navItems = [
  {
    title: 'Projects',
    path: '/projects',
  },
  {
    title: 'Articles',
    path: '/articles',
  },
  {
    title: 'About',
    path: '/about',
  },
] as const

const Home = () => {
  const isBigScreen = useMediaQuery(dt.screen.big)
  const isRoot = useMatch('/')

  const navigate = useNavigate()

  useEffect(() => {
    if (isBigScreen && isRoot) {
      navigate('/projects')
    }
  }, [isBigScreen, isRoot, navigate])

  const navigation = (
    <Nav>
      {navItems.map(({ title, path }) => (
        <StyledNavLink key={title} to={path}>
          {title}
        </StyledNavLink>
      ))}
    </Nav>
  )

  return (
    <Container>
      <Header>
        <LogoWrapper>
          <LogoImg src={logo} alt='Logo' />
          <LogoTitle>
            <LogoSubtitle>RM's</LogoSubtitle>Flower of Ideas
          </LogoTitle>
          <StyledThemeSwitcher />
        </LogoWrapper>
      </Header>
      <Main>
        {isBigScreen ? (
          <>
            {navigation}
            <Outlet />
          </>
        ) : isRoot ? (
          navigation
        ) : (
          <Outlet />
        )}
      </Main>
      <Footer>
        <FooterText>Created by Real_Marshal</FooterText>
        <FooterText>Logo generated by Midjourney AI</FooterText>
      </Footer>
    </Container>
  )
}

export { Home }
